### PR TITLE
Add bash tags/load after/groups from C&PD userlist

### PR DESCRIPTION
**Pull request by pStyl3**
Issue https://github.com/loot/fallout3/issues/84

### CODE REVIEW

**Comment by pStyl3** [comment]
These following plugins still need to be added (I still need to search for them):
- [x] `Fo3HirezdFlamer.esp`
- [x] `Fo3HirezdMinigun.esp`
- [x] `The Mantis Imperative - Nasty Zeta No Scaling.esp`
- [x] `The Mantis Imperative - Nasty Zeta.esp`
- [x] `UF3P - Exotic Caravans.esp` (`UF3P - Exotic Caravans.esm` is in the masterlist)

~~`RubblePilesFix.esp`~~
~~`Weapon Mods Patch.esp`~~
~~`ClearAndPresentAdjustment-GreatOldOnes.esp`~~
~~`ClearAndPresentAdjustment_Beauty_Weapons_2.esp`~~
~~`CPD_Ingestible_Patch.esp`~~

**Comment by pStyl3** [comment]
These following plugins still need to be added (I still need to search for them):
- [ ] `ClearAndPresentAdjustment-GreatOldOnes.esp`
- [ ] `CPD_Ingestible_Patch.esp`
- [ ] `Fo3HirezdFlamer.esp`
- [ ] `Fo3HirezdMinigun.esp`
- [ ] `RubblePilesFix.esp`
- [ ] `The Mantis Imperative - Nasty Zeta No Scaling.esp`
- [ ] `The Mantis Imperative - Nasty Zeta.esp`
- [ ] `UF3P - Exotic Caravans.esp` (`UF3P - Exotic Caravans.esm` is in the masterlist)
- [ ] `Weapon Mods Patch.esp`

**Comment by MacSplody** [comment]
https://www.nexusmods.com/fallout3/mods/19931

Fo3HirezdFlamer.esp
Fo3HirezdMinigun.esp

In the optional deluxe files.

https://www.nexusmods.com/fallout3/mods/21458/
UF3P - Exotic Caravans.esm
UF3P - Exotic Caravans.esp is in old files v1.1 & 1.3

https://www.nexusmods.com/fallout3/mods/12296
Optional files, Nasty Zeta v101
The Mantis Imperative - Nasty Zeta.esp
The Mantis Imperative - Nasty Zeta No Scaling.esp

https://github.com/boss-developers/fallout3/issues/339
RubblePilesFix.esp, deleted mod
UHQ Terrain Overhaul/UHQ Terrain-Roads by printerkop.

**Comment by pStyl3** [comment]
Thanks. For `UF3P - Exotic Caravans.esp` I'm inclined to add `msg: [ *obsolete ]` instead of an after tag for `FO3 Wanderers Edition - Main File.esp`. The new version was released around 2,5 years ago, plenty of time for everyone to get it.

**Comment by MacSplody** [comment]
> I'm inclined to add `msg: [ *obsolete ]` instead of an after tag for `FO3 Wanderers Edition - Main File.esp`

Yeah, an obsolete message would be fine.

**Comment by pStyl3** [comment]
https://forum.step-project.com/topic/5758-general-feedback/page-63#entry185107
`CPD_Ingestible_Patch.esp`
Seems also dead. I can't find the two C&PD plugin mentioned above either.

**Comment by MacSplody** [comment]
> 
> 
> https://forum.step-project.com/topic/5758-general-feedback/page-63#entry185107
> `CPD_Ingestible_Patch.esp`
> Seems also dead. I can't find the two C&PD plugin mentioned above either.

If they can't be sourced then I wouldn't bother adding them.

**Pull request merged**
