### PR TITLE
Update More Perks

### PR DESCRIPTION
**Pull request by MacSplody**
#380

### CODE REVIEW

**Comment by sibir-ine** [comment]
The **Relev** tag is needed to preserve the leveled list flag changes, they're reverted by default without it. Or are they unintentional/not important? (Also the `tag` key should be after the `msg` key.)

**Comment by MacSplody** [comment]
> The **Relev** tag is needed to preserve the leveled list flag changes, they're reverted by default without it.

Relev isn't supposed to carry those changes forward, it happens to do it sometimes.

With a test file, `Dree Perks.esp` & DLC as masters. Delev tag added to test patch, Relev to  `Dree Perks.esp`.

image

image

It would be easier to manage the flags/globals with separate tags.

> (Also the tag key should be after the msg key.)

Do we have the order listed somewhere now?

**Comment by sibir-ine** [comment]
Yeah, the patcher's flag handling behavior is inconsistent at the moment. I don't imagine it's ideal for it to revert those flags by default even if it doesn't forward them in every scenario, but I believe it'll get rewritten at some point anyway so 🤷 

> Do we have the order listed somewhere now?

It's the same order as listed in the [syntax docs](https://loot-api.readthedocs.io/en/stable/metadata/data_structures/plugin.html) (minus `URL`) & that I've been enforcing in reviews for the sake of consistency. It's not too important, but it'd be nice to try to keep things uniform & consistent as we go.

**Comment by MacSplody** [comment]
> Yeah, the patcher's flag handling behavior is inconsistent at the moment. I don't imagine it's ideal for it to revert those flags by default even if it doesn't forward them in every scenario, but I believe it'll get rewritten at some point anyway so 🤷

Well the patcher will start reverting changes in level lists if the wrong files are tagged with **Relev**.
It starts becoming an order issue in that case, you'll then have to give priority to files changing level list over ones modifying the flags. And you may end up losing the flags anyway.

**Pull request merged**
